#!/usr/bin/env just --justfile

[private]
default:
  @just --list --unsorted

[doc('Restore server dependencies')]
restore:
  dotnet restore YACTR.sln

[doc('Run the API with hot reload')]
watch:
  dotnet watch --project src/YACTR.Api

[doc('Formats all code in the project')]
format:
  dotnet format style --diagnostics IDE0005

[group('test')]
[doc('Run the test-profile docker compose and run a test suite with coverage report generation enabled')]
coverage:
  #!/usr/bin/env bash
  set -uo pipefail
  compose="{{justfile_directory()}}/docker-compose.yaml"
  rm -rf tests/YACTR.Api.Tests/TestResults tests/YACTR.Domain.Tests/TestResults tests/YACTR.Infrastructure.Tests/TestResults
  docker compose -f "$compose" --profile test up -d
  dotnet test YACTR.sln --settings ./tests.runsettings --verbosity minimal --collect:"XPlat Code Coverage" || true
  docker compose -f "$compose" --profile test down
  reportgenerator \
    -reports:"tests/**/TestResults/**/coverage.cobertura.xml" \
    -targetdir:"coverage-report" \
    -reporttypes:Html
  open coverage-report/index.html

[group('database')]
[doc('Runs migrations against the dev-profile docker-compose')]
run-migrations environment='development':
    ASPNETCORE_ENVIRONMENT={{environment}} dotnet ef database update --project src/YACTR.Infrastructure --startup-project src/YACTR.Api

[group('database')]
[doc('Creates a migration in the project')]
add-migration migration_name:
    dotnet ef migrations add {{migration_name}} --project src/YACTR.Infrastructure --startup-project src/YACTR.Api -c DatabaseContext

[group('database')]
[doc('Removes the latest migration and recreates it, optionally with a new name')]
recreate-latest-migration new_name='':
    #!/usr/bin/env bash
    if [ -z "{{new_name}}" ]; then
        migration_name=$(dotnet ef migrations list --project src/YACTR.Infrastructure --startup-project src/YACTR.Api -c DatabaseContext \
            | tail -n 1 | sed -nE 's/^[^_]+_([^ ]+).*/\1/p')
    else
        migration_name="{{new_name}}"
    fi
    echo "Recreating latest migration with name: $migration_name"
    dotnet ef migrations remove --project src/YACTR.Infrastructure --startup-project src/YACTR.Api -c DatabaseContext &> /dev/null && echo "Migration removed successfully"
    dotnet ef migrations add "$migration_name" --project src/YACTR.Infrastructure --startup-project src/YACTR.Api -c DatabaseContext &> /dev/null && echo "Migration created successfully"

[group('database')]
[doc('Rolls back the database to a given migration')]
db-rollback migration_name:
    dotnet ef database update {{migration_name}} --project src/YACTR

[group('database')]
[doc('Truncates all tables in the local database, development or test')]
truncate-local-db environment='development':
    PGPASSWORD=yactr psql -h localhost -U yactr -d {{ if environment == 'development' {"yactr"} else {"yactr_test"} }} \
    -c "DO \$\$ DECLARE r RECORD; BEGIN SET session_replication_role = replica; FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename <> 'migrations' AND tablename <> 'users' and tablename <> 'country_data') LOOP EXECUTE 'TRUNCATE TABLE ' || quote_ident(r.tablename) || ' CASCADE'; END LOOP; SET session_replication_role = DEFAULT; RAISE NOTICE 'All tables in public schema have been truncated successfully.'; END \$\$"
