// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YACTR.Data;
using YACTR.Data.Model.Authorization.Permissions;
using YACTR.Data.Model.Climbing;

#nullable disable

namespace YACTR.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251011121302_AlterTableRemoveImageKeyAndBucket")]
    partial class AlterTableRemoveImageKeyAndBucket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "climbing_type", new[] { "sport", "traditional", "boulder", "mixed", "aid" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YACTR.Data.Model.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("YACTR.Data.Model.Organizations.OrganizationTeamUser", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("OrganizationTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<ICollection<Permission>>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.HasKey("OrganizationId", "OrganizationTeamId", "UserId")
                        .HasName("pk_organization_team_users");

                    b.HasIndex("OrganizationTeamId")
                        .HasDatabaseName("ix_organization_team_users_organization_team_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_team_users_user_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .HasDatabaseName("ix_organization_team_users_organization_id_user_id");

                    b.ToTable("organization_team_users", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Organizations.OrganizationUser", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.PrimitiveCollection<ICollection<Permission>>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.HasKey("OrganizationId", "UserId")
                        .HasName("pk_organization_users");

                    b.HasIndex("Permissions")
                        .HasDatabaseName("ix_organization_users_permissions");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Permissions"), "gin");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_users_user_id");

                    b.ToTable("organization_users", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Achievement.Ascent", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<Instant>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_ascents_route_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ascents_user_id");

                    b.ToTable("ascents", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Authentication.User", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<ICollection<Permission>>("AdminPermissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("admin_permissions");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth0_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Instant>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<ICollection<Permission>>("PlatformPermissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("platform_permissions");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasIndex("Auth0UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth0_user_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Area", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<MultiPolygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("boundary");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("location");

                    b.Property<Guid?>("MaintainerOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintainer_organization_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasIndex("MaintainerOrganizationId")
                        .HasDatabaseName("ix_areas_maintainer_organization_id");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Pitch", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PitchOrder")
                        .HasColumnType("integer")
                        .HasColumnName("pitch_order");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<Guid?>("RouteSvgOverlayId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_svg_overlay_id");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<ClimbingType>("Type")
                        .HasColumnType("climbing_type")
                        .HasColumnName("type");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_pitches_route_id");

                    b.HasIndex("RouteSvgOverlayId")
                        .IsUnique()
                        .HasDatabaseName("ix_pitches_route_svg_overlay_id");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_pitches_sector_id");

                    b.ToTable("pitches", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Rating.RouteLike", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_route_likes_route_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_route_likes_user_id");

                    b.ToTable("route_likes", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Rating.RouteRating", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_route_ratings_route_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_route_ratings_user_id");

                    b.ToTable("route_ratings", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Route", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<string>("BolterName")
                        .HasColumnType("text")
                        .HasColumnName("bolter_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FirstAscentClimberName")
                        .HasColumnType("text")
                        .HasColumnName("first_ascent_climber_name");

                    b.Property<Instant?>("FirstAscentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_ascent_date");

                    b.Property<string>("Grade")
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<Guid?>("SectorSvgOverlayId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_svg_overlay_id");

                    b.Property<Guid?>("TopoImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("topo_image_id");

                    b.Property<Guid?>("TopoImageOverlaySvgId")
                        .HasColumnType("uuid")
                        .HasColumnName("topo_image_overlay_svg_id");

                    b.Property<ClimbingType>("Type")
                        .HasColumnType("climbing_type")
                        .HasColumnName("type");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_routes_sector_id");

                    b.HasIndex("SectorSvgOverlayId")
                        .IsUnique()
                        .HasDatabaseName("ix_routes_sector_svg_overlay_id");

                    b.HasIndex("TopoImageId")
                        .IsUnique()
                        .HasDatabaseName("ix_routes_topo_image_id");

                    b.HasIndex("TopoImageOverlaySvgId")
                        .IsUnique()
                        .HasDatabaseName("ix_routes_topo_image_overlay_svg_id");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Sector", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<LineString>("ApproachPath")
                        .HasColumnType("geometry")
                        .HasColumnName("approach_path");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<Point>("EntryPoint")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("entry_point");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Point>("RecommendedParkingLocation")
                        .HasColumnType("geometry")
                        .HasColumnName("recommended_parking_location");

                    b.Property<Polygon>("SectorArea")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("sector_area");

                    b.Property<Guid?>("SectorImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_image_id");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_sectors_area_id");

                    b.HasIndex("SectorImageId")
                        .IsUnique()
                        .HasDatabaseName("ix_sectors_sector_image_id");

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Image", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("ix_images_uploader_id");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Organizations.Organization", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Organizations.OrganizationTeam", b =>
                {
                    b.HasBaseType("YACTR.Data.Model.BaseEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_teams_organization_id");

                    b.ToTable("organization_teams", (string)null);
                });

            modelBuilder.Entity("YACTR.Data.Model.Organizations.OrganizationTeamUser", b =>
                {
                    b.HasOne("YACTR.Data.Model.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_team_users_organizations_organization_id");

                    b.HasOne("YACTR.Data.Model.Organizations.OrganizationTeam", "OrganizationTeam")
                        .WithMany("OrganizationTeamUsers")
                        .HasForeignKey("OrganizationTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_team_users_organization_teams_organization_tea");

                    b.HasOne("YACTR.Data.Model.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_team_users_users_user_id");

                    b.HasOne("YACTR.Data.Model.Organizations.OrganizationUser", "OrganizationUser")
                        .WithMany("OrganizationTeamUsers")
                        .HasForeignKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_team_users_organization_users_organization_id_");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationTeam");

                    b.Navigation("OrganizationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YACTR.Data.Model.Organizations.OrganizationUser", b =>
                {
                    b.HasOne("YACTR.Data.Model.Organizations.Organization", "Organization")
                        .WithMany("OrganizationUsers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_users_organizations_organization_id");

                    b.HasOne("YACTR.Data.Model.Authentication.User", "User")
                        .WithMany("OrganizationUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_users_users_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YACTR.Data.Model.Achievement.Ascent", b =>
                {
                    b.HasOne("YACTR.Data.Model.Climbing.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ascents_routes_route_id");

                    b.HasOne("YACTR.Data.Model.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ascents_users_user_id");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Area", b =>
                {
                    b.HasOne("YACTR.Data.Model.Organizations.Organization", "MaintainerOrganization")
                        .WithMany()
                        .HasForeignKey("MaintainerOrganizationId")
                        .HasConstraintName("fk_areas_organizations_maintainer_organization_id");

                    b.Navigation("MaintainerOrganization");
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Pitch", b =>
                {
                    b.HasOne("YACTR.Data.Model.Climbing.Route", "Route")
                        .WithMany("Pitches")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pitches_routes_route_id");

                    b.HasOne("YACTR.Data.Model.Image", "RouteSvgOverlay")
                        .WithOne()
                        .HasForeignKey("YACTR.Data.Model.Climbing.Pitch", "RouteSvgOverlayId")
                        .HasConstraintName("fk_pitches_images_route_svg_overlay_id");

                    b.HasOne("YACTR.Data.Model.Climbing.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pitches_sectors_sector_id");

                    b.Navigation("Route");

                    b.Navigation("RouteSvgOverlay");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Rating.RouteLike", b =>
                {
                    b.HasOne("YACTR.Data.Model.Climbing.Route", "Route")
                        .WithMany("RouteLikes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_route_likes_routes_route_id");

                    b.HasOne("YACTR.Data.Model.Authentication.User", "User")
                        .WithMany("RouteLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_route_likes_users_user_id");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Rating.RouteRating", b =>
                {
                    b.HasOne("YACTR.Data.Model.Climbing.Route", "Route")
                        .WithMany("RouteRatings")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_route_ratings_routes_route_id");

                    b.HasOne("YACTR.Data.Model.Authentication.User", "User")
                        .WithMany("RouteRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_route_ratings_users_user_id");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Route", b =>
                {
                    b.HasOne("YACTR.Data.Model.Climbing.Sector", "Sector")
                        .WithMany("Routes")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routes_sectors_sector_id");

                    b.HasOne("YACTR.Data.Model.Image", "SectorSvgOverlay")
                        .WithOne()
                        .HasForeignKey("YACTR.Data.Model.Climbing.Route", "SectorSvgOverlayId")
                        .HasConstraintName("fk_routes_images_sector_svg_overlay_id");

                    b.HasOne("YACTR.Data.Model.Image", "TopoImage")
                        .WithOne()
                        .HasForeignKey("YACTR.Data.Model.Climbing.Route", "TopoImageId")
                        .HasConstraintName("fk_routes_images_topo_image_id");

                    b.HasOne("YACTR.Data.Model.Image", "TopoImageOverlaySvg")
                        .WithOne()
                        .HasForeignKey("YACTR.Data.Model.Climbing.Route", "TopoImageOverlaySvgId")
                        .HasConstraintName("fk_routes_images_topo_image_overlay_svg_id");

                    b.Navigation("Sector");

                    b.Navigation("SectorSvgOverlay");

                    b.Navigation("TopoImage");

                    b.Navigation("TopoImageOverlaySvg");
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Sector", b =>
                {
                    b.HasOne("YACTR.Data.Model.Climbing.Area", "Area")
                        .WithMany("Sectors")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sectors_areas_area_id");

                    b.HasOne("YACTR.Data.Model.Image", "SectorImage")
                        .WithOne()
                        .HasForeignKey("YACTR.Data.Model.Climbing.Sector", "SectorImageId")
                        .HasConstraintName("fk_sectors_images_sector_image_id");

                    b.Navigation("Area");

                    b.Navigation("SectorImage");
                });

            modelBuilder.Entity("YACTR.Data.Model.Image", b =>
                {
                    b.HasOne("YACTR.Data.Model.Authentication.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .HasConstraintName("fk_images_users_uploader_id");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("YACTR.Data.Model.Organizations.OrganizationTeam", b =>
                {
                    b.HasOne("YACTR.Data.Model.Organizations.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_teams_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("YACTR.Data.Model.Organizations.OrganizationUser", b =>
                {
                    b.Navigation("OrganizationTeamUsers");
                });

            modelBuilder.Entity("YACTR.Data.Model.Authentication.User", b =>
                {
                    b.Navigation("OrganizationUsers");

                    b.Navigation("RouteLikes");

                    b.Navigation("RouteRatings");
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Area", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Route", b =>
                {
                    b.Navigation("Pitches");

                    b.Navigation("RouteLikes");

                    b.Navigation("RouteRatings");
                });

            modelBuilder.Entity("YACTR.Data.Model.Climbing.Sector", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("YACTR.Data.Model.Organizations.Organization", b =>
                {
                    b.Navigation("OrganizationUsers");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("YACTR.Data.Model.Organizations.OrganizationTeam", b =>
                {
                    b.Navigation("OrganizationTeamUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
